parse PKGBUILD to find the Github user and project

diff --git a/autopkg b/autopkg
--- a/autopkg
+++ b/autopkg
@@ -1,39 +1,32 @@
 #! /bin/sh
 
-# Auto-update script for simple MinGW packages where the upstream source
-# is on GitHub.
+# Auto-update script for simple (meaning consisting of exactly one source file)
+# MinGW packages where the upstream source is on GitHub.
+
+set -eu -o pipefail
 
 die() { echo "$@" >&2; exit 1; }
 
-usage() {
-    echo "\
-Usage: $0 <account>/<project>
-
-E.g. '$0 fmtlib/fmt'"
-    exit $1
-}
-
-[ -z "$1" ] && usage 2
-[ $1 = -h ] && usage
-case $1 in
-    */*) ;;
-    *) usage 2 ;;
-esac
+[ -z "${1:-}" ] || die "no arguments expected"
 [ -f PKGBUILD ] || die "PKGBUILD not found; not in a package directory?"
 
-set -eux -o pipefail
+user=$(sed -ne '/^source=/s!.*github\.com/\([^/]*\).*!\1!p' PKGBUILD)
+[ -n "$user" ] || die "github user name not found in 'source' URL"
+proj=$(sed -ne '/^_realname=/s/.*=//p' PKGBUILD)
+[ -n "$proj" ] || die "project name not found in '_realname' setting"
 
 rm -rf pkg/ src/
 
-tag=$(curl -sS https://api.github.com/repos/$1/releases/latest |
+tag=$(curl -sS https://api.github.com/repos/$user/$proj/releases/latest |
     jq -r .tag_name | sed s/^v//)
 sed -i -e "/^pkgver=/s/.*/pkgver=$tag/" PKGBUILD
+
+echo "building $proj-$tag from github.com/$user/$proj"
 
 sums="$(makepkg -g)"
 sed -i -e "/^sha256sums=/s/.*/$sums/" PKGBUILD
 
 makepkg-mingw -c
 
-proj=${1#*/}
 git checkout -b $proj-$tag master
 git commit -a -m"$proj: update to $tag"
